#!/bin/bash
POSIXLY_CORRECT=yes
arg_count=$#
if [[ ($arg_count -eq 1 && ("$1" == "--help" || "$1" == '-h')) || $arg_count -eq 0 ]]; then
  echo "Called help"
  exit 0
fi





if [[ "$1"=="list" ]]; then
 cat "${*: -1}" | grep "$2;"
 exit 0
fi








#What the hell is going on here????
if [[ $arg_count -eq 2 ]]; then
 cat "$2" | grep "$1;" | sort -r 
 exit 0
fi
